let playerModel = require('../model/player')
const factory = require('../factory')
exports.addPlayer =   factory.addOne(playerModel)
exports.findall =  factory.findall(playerModel)
exports.getById = factory.getById(playerModel)
exports.findOne  = factory.findOne(playerModel)
exports.deleteOne = factory.deleteOne(playerModel)