let userModel = require('../model/user')
const factory = require('../factory')
exports.addUser =   factory.addOne(userModel)
exports.findall =  factory.findall(userModel)
exports.getById = factory.getById(userModel)
exports.findOne = factory.findOne(userModel)
exports.deleteOne = factory.deleteOne(userModel)